sudo: false
language: java
jdk:
  - oraclejdk8

before_install:
  - git clone https://github.com/SpoonLabs/gumtree-spoon-ast-diff.git gumtree
  - cd gumtree
  - mvn install -Dmaven.test.skip=true
  - cd ..

script:
  - mvn verify jacoco:report coveralls:report

cache:
  directories:
    - $HOME/.m2
